"""Initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-12 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    
    # Create widgets table
    op.create_table('widgets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('form_fields', sa.JSON(), nullable=False),
    sa.Column('button_text', sa.String(length=50), nullable=False),
    sa.Column('display_options', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widgets_id'), 'widgets', ['id'], unique=False)
    op.create_index(op.f('ix_widgets_owner_id'), 'widgets', ['owner_id'], unique=False)
    
    # Create submissions table
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('submitted_data', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_created_at'), 'submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_index(op.f('ix_submissions_idempotency_key'), 'submissions', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_submissions_tenant_id'), 'submissions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_submissions_widget_id'), 'submissions', ['widget_id'], unique=False)
    op.create_index('idx_idempotency_widget', 'submissions', ['idempotency_key', 'widget_id'], unique=True)
    op.create_index('idx_tenant_created', 'submissions', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_widget_tenant', 'submissions', ['widget_id', 'tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_widget_tenant', table_name='submissions')
    op.drop_index('idx_tenant_created', table_name='submissions')
    op.drop_index('idx_idempotency_widget', table_name='submissions')
    op.drop_index(op.f('ix_submissions_widget_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_tenant_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_idempotency_key'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_created_at'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_widgets_owner_id'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_id'), table_name='widgets')
    op.drop_table('widgets')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###